#!/usr/bin/env python3
"""
Download AI-generated JPEG covers for blog articles from Pollinations (turbo).

Reads article JSON files generated by generate-1000-blog.py, fetches the
imagePrompt from each, and saves the cover to:
    client/public/assets/blog/covers/<slug>.jpg

Usage:
    python3 scripts/download-blog-covers.py

The script is resumable: it skips slugs that already have a non-empty JPG.
"""

import argparse
import json
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARTICLES_DIR = ROOT / "client" / "public" / "assets" / "blog" / "articles"
COVERS_DIR = ROOT / "client" / "public" / "assets" / "blog" / "covers"
INDEX_PATH = ROOT / "client" / "public" / "assets" / "blog" / "articles-index.json"

POLLINATIONS_URL = "https://image.pollinations.ai/prompt/{prompt}"
DEFAULT_PARAMS = {
    "width": "1200",
    "height": "630",
    "nologo": "true",
    "model": "turbo",
    "seed": "42",
}


def fetch_image(prompt: str, seed: int, retries: int = 3) -> bytes:
    params = dict(DEFAULT_PARAMS)
    params["seed"] = str(seed)
    url = POLLINATIONS_URL.format(prompt=urllib.parse.quote(prompt)) + "?" + urllib.parse.urlencode(params)
    headers = {
        "User-Agent": "Mozilla/5.0 (compatible; FreonnBot/1.0; +https://freonn.ru)",
        "Accept": "image/jpeg,image/png,image/webp,*/*",
    }

    last_error = None
    for attempt in range(retries):
        req = urllib.request.Request(url, headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=90) as resp:
                data = resp.read()
            if len(data) < 1000:
                raise RuntimeError(f"Response too small ({len(data)} bytes)")
            if data[:2] not in (b"\xff\xd8", b"\x89PNG"):
                raise RuntimeError(f"Unexpected image magic: {data[:4].hex()}")
            return data
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError, RuntimeError) as e:
            last_error = e
            wait = 2 * (attempt + 1)
            print(f"  attempt {attempt + 1} failed: {e}, retrying in {wait}s...")
            time.sleep(wait)
    raise RuntimeError(f"Could not download image after {retries} attempts: {last_error}")


def main():
    parser = argparse.ArgumentParser(description="Download blog cover images from Pollinations")
    parser.add_argument("--limit", type=int, default=None, help="Download only the first N covers")
    args = parser.parse_args()

    COVERS_DIR.mkdir(parents=True, exist_ok=True)

    if not ARTICLES_DIR.exists():
        raise RuntimeError(f"Articles directory not found: {ARTICLES_DIR}")

    article_files = sorted(ARTICLES_DIR.glob("*.json"))
    if args.limit:
        article_files = article_files[:args.limit]
    if not article_files:
        raise RuntimeError("No article JSON files found. Run generate-1000-blog.py first.")

    # Build list of articles that need covers
    to_download = []
    for path in article_files:
        article = json.loads(path.read_text(encoding="utf-8"))
        slug = article.get("slug", path.stem)
        cover_path = COVERS_DIR / f"{slug}.jpg"
        if cover_path.exists() and cover_path.stat().st_size > 1000:
            continue
        prompt = article.get("imagePrompt") or article.get("title")
        to_download.append({
            "slug": slug,
            "prompt": prompt,
            "path": cover_path,
            "json_path": path,
            "article": article,
        })

    print(f"Total articles: {len(article_files)}")
    print(f"Covers to download: {len(to_download)}")

    for i, item in enumerate(to_download, 1):
        slug = item["slug"]
        prompt = item["prompt"]
        cover_path = item["path"]
        print(f"[{i}/{len(to_download)}] {slug}")
        try:
            # Vary seed by slug to make covers unique even for identical prompts
            seed = hash(slug) % 10_000_000
            data = fetch_image(prompt, seed=seed)
            cover_path.write_bytes(data)
            print(f"  -> {len(data)} bytes")
            # Brief pause to respect the free rate limit
            time.sleep(0.3)
        except Exception as e:
            print(f"  ERROR: {e}")
            # Continue with the rest; can be re-run later

    # Update article JSON and index to point to JPG covers
    for path in article_files:
        article = json.loads(path.read_text(encoding="utf-8"))
        slug = article.get("slug", path.stem)
        cover_path = COVERS_DIR / f"{slug}.jpg"
        if cover_path.exists() and cover_path.stat().st_size > 1000:
            article["img"] = f"/assets/blog/covers/{slug}.jpg"
        path.write_text(json.dumps(article, ensure_ascii=False, indent=2), encoding="utf-8")

    if INDEX_PATH.exists():
        index = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
        for entry in index:
            slug = entry.get("slug")
            cover_path = COVERS_DIR / f"{slug}.jpg"
            if slug and cover_path.exists() and cover_path.stat().st_size > 1000:
                entry["img"] = f"/assets/blog/covers/{slug}.jpg"
        INDEX_PATH.write_text(json.dumps(index, ensure_ascii=False, indent=2), encoding="utf-8")

    downloaded = sum(1 for p in COVERS_DIR.glob("*.jpg") if p.stat().st_size > 1000)
    print(f"\nDone. JPG covers available: {downloaded}/{len(article_files)}")


if __name__ == "__main__":
    main()
