#!/usr/bin/env python3
"""
Generate a small AI cover image library for blog articles and copy the best
matching image to each article's cover slot.

Instead of generating 1000 unique images (too slow / expensive on free APIs),
we generate one realistic AI photo per (service, object) pair and copy it to all
articles that share that pair. This gives every article a relevant cover while
staying within reasonable time/budget limits.

Usage:
    python3 scripts/generate-blog-cover-library.py

Requires articles generated by generate-1000-blog.py first.
"""

import json
import shutil
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARTICLES_DIR = ROOT / "client" / "public" / "assets" / "blog" / "articles"
COVERS_DIR = ROOT / "client" / "public" / "assets" / "blog" / "covers"
LIBRARY_DIR = ROOT / "client" / "public" / "assets" / "blog" / "cover-library"
INDEX_PATH = ROOT / "client" / "public" / "assets" / "blog" / "articles-index.json"

POLLINATIONS_URL = "https://image.pollinations.ai/prompt/{prompt}"
DEFAULT_PARAMS = {
    "width": "1200",
    "height": "630",
    "nologo": "true",
    "model": "turbo",
    "seed": "42",
}


def fetch_image(prompt: str, seed: int, retries: int = 3) -> bytes:
    params = dict(DEFAULT_PARAMS)
    params["seed"] = str(seed)
    url = POLLINATIONS_URL.format(prompt=urllib.parse.quote(prompt)) + "?" + urllib.parse.urlencode(params)
    headers = {
        "User-Agent": "Mozilla/5.0 (compatible; FreonnBot/1.0; +https://freonn.ru)",
        "Accept": "image/jpeg,image/png,image/webp,*/*",
    }

    last_error = None
    for attempt in range(retries):
        req = urllib.request.Request(url, headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=90) as resp:
                data = resp.read()
            if len(data) < 1000:
                raise RuntimeError(f"Response too small ({len(data)} bytes)")
            if data[:2] not in (b"\xff\xd8", b"\x89PNG"):
                raise RuntimeError(f"Unexpected image magic: {data[:4].hex()}")
            return data
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError, RuntimeError) as e:
            last_error = e
            wait = 2 * (attempt + 1)
            print(f"  attempt {attempt + 1} failed: {e}, retrying in {wait}s...", flush=True)
            time.sleep(wait)
    raise RuntimeError(f"Could not download image after {retries} attempts: {last_error}")


def main():
    COVERS_DIR.mkdir(parents=True, exist_ok=True)
    LIBRARY_DIR.mkdir(parents=True, exist_ok=True)

    if not ARTICLES_DIR.exists():
        raise RuntimeError(f"Articles directory not found: {ARTICLES_DIR}")

    articles = []
    for path in sorted(ARTICLES_DIR.glob("*.json")):
        article = json.loads(path.read_text(encoding="utf-8"))
        article["_path"] = path
        articles.append(article)

    if not articles:
        raise RuntimeError("No article JSON files found. Run generate-1000-blog.py first.")

    # Group articles by (service, object) pair
    groups: dict[tuple[str, str], list[dict]] = {}
    for article in articles:
        key = (article.get("serviceSlug", "other"), article.get("objectSlug", "other"))
        groups.setdefault(key, []).append(article)

    print(f"Total articles: {len(articles)}")
    print(f"Unique (service, object) pairs: {len(groups)}")

    # Generate / fetch library image for each pair
    for i, ((service_slug, object_slug), group) in enumerate(sorted(groups.items()), 1):
        key = f"{service_slug}_{object_slug}"
        lib_path = LIBRARY_DIR / f"{key}.jpg"

        if lib_path.exists() and lib_path.stat().st_size > 1000:
            print(f"[{i}/{len(groups)}] {key}: using existing library image")
        else:
            # Use the first article's prompt for this pair; it already contains service/object/city context
            prompt = group[0].get("imagePrompt") or group[0].get("title", "engineering systems")
            seed = hash(key) % 10_000_000
            print(f"[{i}/{len(groups)}] {key}: downloading cover image...", flush=True)
            try:
                data = fetch_image(prompt, seed=seed)
                lib_path.write_bytes(data)
                print(f"  -> {len(data)} bytes", flush=True)
            except Exception as e:
                print(f"  ERROR: {e}", flush=True)
                continue
            time.sleep(0.5)

        if not lib_path.exists() or lib_path.stat().st_size < 1000:
            continue

        # Copy the library image to every article cover in this group
        for article in group:
            slug = article["slug"]
            cover_path = COVERS_DIR / f"{slug}.jpg"
            if cover_path.exists() and cover_path.stat().st_size > 1000:
                continue
            shutil.copy2(lib_path, cover_path)
            article["img"] = f"/assets/blog/covers/{slug}.jpg"

    # Save updated article JSONs
    for article in articles:
        path = article.pop("_path")
        path.write_text(json.dumps(article, ensure_ascii=False, indent=2), encoding="utf-8")

    # Update index
    if INDEX_PATH.exists():
        index = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
        slug_to_img = {a["slug"]: a["img"] for a in articles}
        for entry in index:
            if entry["slug"] in slug_to_img:
                entry["img"] = slug_to_img[entry["slug"]]
        INDEX_PATH.write_text(json.dumps(index, ensure_ascii=False, indent=2), encoding="utf-8")

    jpg_covers = len([p for p in COVERS_DIR.glob("*.jpg") if p.stat().st_size > 1000])
    print(f"\nDone. JPG covers applied: {jpg_covers}/{len(articles)}")


if __name__ == "__main__":
    main()
